### ISSUE TITLE
PDF version of the ebook missing Devanagari texts 

### ISSUE THREAD

**Issue by enathu** [fontforge/designwithfontforge.com#99] opened 2015-05-14 08:14 UTC
The PDF output of the ebook is not rendered any Devanagari texts. The missing texts are vital information for the context of the book. As you can see in this example. 

![Devanagari texts missing](https://cloud.githubusercontent.com/assets/62147/7628273/4157c4e4-fa19-11e4-959c-c383cf0c68c9.jpg)

Some possible workarounds are
- embedding those text blocks as images in the page
  or 
- using a different kind of PDF generate engine to render the Devanagari text.

Thanks.

**Comment by JohnWong** [comment] 2015-05-16 16:00
The pdf file is generated by [gitbook](https://www.gitbook.com/book/yellowxz/designwithfontforge/details).    Does anyone know how to fix it?

**Comment by JoesCat** [comment] 2015-05-16 16:08
On May 16, 2015 09:00:49 AM John Wong wrote:

> The pdf file is generated by
> [gitbook](https://www.gitbook.com/book/yellowxz/designwithfontforge/det
> ails).    Does anyone know how to fix it.

Contact the website through the contact page.
indicate where the problem is.

I imagine it is a case where it needs to "import" a font, or the current 
font does not contain those characters, either way, it may be a bug for 
them to fix nd improve.

**Comment by jrbastien** [comment] 2017-04-10 02:20
I have just regenerated them with Gitbook 3.2.2 and the problem is gone.  I have submitted a pull request with the new books.

**Comment by jrbastien** [comment] 2017-04-12 00:14
Now fixed

**Closed as completed by jrbastien** 2017-04-12 00:14 UTC
